language: php
php:
  - 5.6
  - 5.5
before_install:
  - composer self-update
  - composer install
script:
  - composer test
after_script:
  - php bin/coverallskit send .cli-coveralls.yml
notifications:
  email: false
sudo: false
