[target]

# Include source files.
includes = ["src"]

# Exclude source files.
excludes = ["vendor", "spec"]

[report]
reportDirectory = "."

[report.coverageBounds]
satisfactory = 70.0
critical = 35.0

[reporter]

# LcovReporter
[reporter.lcov]
fileName = "report.lcov"

# TextReporter
[reporter.text]

# ProcessingTimeReporter
[reporter.processingTime]
